### ISSUE TITLE
rolling back sometimes throws a 500, but still creates a new version

### ISSUE THREAD

**Issue by arschles** [deis/controller#187]
given the following releases:

```console
ENG000656:workflow aaronschlesinger$ deis releases:list -a app2
=== app2 Releases
v12	2015-12-22T21:26:57UTC	arschles rolled back to v10
v11	2015-12-22T21:25:53UTC	arschles rolled back to v3
v10	2015-12-22T21:25:46UTC	arschles rolled back to v4
v9	2015-12-22T21:25:32UTC	arschles rolled back to v5
v8	2015-12-22T21:25:25UTC	arschles rolled back to v4
v7	2015-12-22T21:25:14UTC	arschles rolled back to v5
v6	2015-12-22T21:24:50UTC	arschles rolled back to v1
v5	2015-12-22T21:24:17UTC	arschles rolled back to v3
v4	2015-12-22T21:24:13UTC	arschles rolled back to v1
v3	2015-12-22T21:23:48UTC	arschles rolled back to v2
v2	2015-12-22T21:22:02UTC	arschles deployed deis/example-go
v1	2015-12-22T21:20:31UTC	arschles created initial release
```

I haven't been able to reliably reproduce which rollbacks return 500, but neither the latest nor 2nd to latest version have thrown errors. When I do get an error, however, a new release is created:

```console
ENG000656:workflow aaronschlesinger$ deis releases:rollback v11 -a app2
Rolling back to v11... done, v13
ENG000656:workflow aaronschlesinger$ deis releases:rollback v10 -a app2
Rolling back to v10... Error: 
500 INTERNAL SERVER ERROR
<h1>Server Error (500)</h1>
ENG000656:workflow aaronschlesinger$ deis releases:list -a app2
=== app2 Releases
v14	2015-12-22T21:28:49UTC	arschles rolled back to v10
v13	2015-12-22T21:28:31UTC	arschles rolled back to v11
v12	2015-12-22T21:26:57UTC	arschles rolled back to v10
v11	2015-12-22T21:25:53UTC	arschles rolled back to v3
v10	2015-12-22T21:25:46UTC	arschles rolled back to v4
v9	2015-12-22T21:25:32UTC	arschles rolled back to v5
v8	2015-12-22T21:25:25UTC	arschles rolled back to v4
v7	2015-12-22T21:25:14UTC	arschles rolled back to v5
v6	2015-12-22T21:24:50UTC	arschles rolled back to v1
v5	2015-12-22T21:24:17UTC	arschles rolled back to v3
v4	2015-12-22T21:24:13UTC	arschles rolled back to v1
v3	2015-12-22T21:23:48UTC	arschles rolled back to v2
v2	2015-12-22T21:22:02UTC	arschles deployed deis/example-go
v1	2015-12-22T21:20:31UTC	arschles created initial release
```

Notice that, since only 1 of the 2 rollbacks succeeded, only one new version should be popped onto the stack, making `v14` invalid.

**Comment by bacongobbler** [comment]
This has always been the case. Even through the release may not have been published to kubernetes via some scheduler error, we still intend to create the release object. Perhaps this would be better resolved by throwing a more informative error?

In any case I don't think this is something we need to target for beta1 since this has always been its behaviour.

**Comment by arschles** [comment]
@bacongobbler @helgi should we close this? Not sure how https://github.com/helgi/controller/commit/f5d3d7701a0e30894538b214eb186d5067fc3660 affected it (as that commit says in its comments), if this is a wont-fix or other.

For now, punting to beta4

**Comment by helgi** [comment]
I haven't been able to prove that it is still a problem, nor not a problem. I referenced the relevant tickets for investigation at a later time. Punting is fine

**Comment by helgi** [comment]
The error handling logic is much improved around all of this. Going to close this until we start seeing this crop up again
